Repository process-engine/bpmn-studio, pull requests merged in 2018-10, with the labels that each got.

#934 ✨ Add an Icon Which Indicates, If a Diagram Is Opened from the Filesystem or a ProcessEngine
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/modules/diagram-detail/diagram-detail.ts
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.scss
  src/modules/navbar/navbar.ts
  src/modules/processdef-detail/processdef-detail.ts
Labels: UI, UX

#913 💄 (50 [-47] shades of bpmn-studio) Add a global button class to define a global button color
  src/app.scss
  src/modules/bpmn-io/bpmn-io.html
  src/modules/bpmn-io/bpmn-io.scss
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/diagram-tools-right/diagram-tools-right.html
  src/modules/diagram-tools-right/diagram-tools-right.scss
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.scss
  src/modules/property-panel/indextabs/extensions/sections/basics/basics.html
  src/modules/property-panel/indextabs/extensions/sections/process/process.html
  src/modules/property-panel/indextabs/forms/sections/basics/basics.html
  src/modules/property-panel/indextabs/general/sections/error-event/error-event.html
  src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html
  src/modules/property-panel/indextabs/general/sections/message-event/message-event.html
  src/modules/property-panel/indextabs/general/sections/message-task/message-task.html
  src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html
  src/modules/property-panel/styles/sections.scss
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.html
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.scss
Labels: code-quality

#998 💄Center the Image on the Start Page
  src/modules/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss
  src/modules/start-page/start-page.html
  src/modules/start-page/start-page.scss
Labels: UI

#1021 🐛 Fix Open Single Diagram Dialog
  electron_app/electron.js
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
Labels: bugfix, windows

#1018 🐛 Fix Auto Update on Windows
  electron_app/electron.js
  package.json
  src/main.ts
Labels: discussion

#1019 💄Unify Confirm buttons
  src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.html
  src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.scss
Labels: bugfix

#1022 ✨ Show Invalid Characters When Entering a Name for a New Diagram
  src/contracts/user-input-validation/IUserInputValidationRule.ts
  src/contracts/user-input-validation/index.ts
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
Labels: feature

#1061 ✨Add a help menu with useful links to the Title Bar
  electron_app/electron.js
Labels: feature

#1089 🐛Fix Call Activity Navigate to Process button
  src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html
Labels: bugfix
