Repository process-engine/bpmn-studio, pull requests merged in 2018-09, with the labels that each got.

#887 💄 Add tooltips to the colorpicker and SolutionExplorer index cards
  src/modules/diagram-tools-right/diagram-tools-right.html
  src/modules/process-solution-panel/process-solution-panel.html
Labels: UX, enhancement

#903 🚸 Change the description of the user task form field types.
  src/modules/property-panel/indextabs/forms/sections/basics/basics.html
Labels: UX, usability

#857 ✅ Create XML View Tests and refactor dependencies
  src/modules/bpmn-io/bpmn-io.html
  src/modules/status-bar/status-bar.html
  test/e2e/src/bpmnXmlView.spec.ts
  test/e2e/src/dashboard.spec.ts
  test/e2e/src/navBar.spec.ts
  test/e2e/src/pages/bpmn-io.ts
  test/e2e/src/pages/bpmnXmlView.ts
  test/e2e/src/pages/navBar.ts
  test/e2e/src/pages/solutionExplorer.ts
  test/e2e/src/pages/statusBar.ts
  test/e2e/src/solutionExplorer.spec.ts
  tslint.json
Labels: integration-test

#890 💄♻️Disable the Distribute Element buttons, refactor colorpicker events
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/diagram-tools-right/diagram-tools-right.html
  src/modules/diagram-tools-right/diagram-tools-right.ts
Labels: UX, code-quality

#909 🐛 Fix lost command stack when opening the xml- or diff - view.
  src/modules/bpmn-io/bpmn-io.html
  src/modules/bpmn-io/bpmn-io.ts
Labels: bugfix

#908 ♻️🔥Remove XML Beautifier
  package.json
  src/contracts/bpmnmodeler/IBpmnModeler.ts
  src/contracts/bpmnmodeler/IBpmnXmlSaveOptions.ts
  src/contracts/bpmnmodeler/index.ts
  src/modules/bpmn-diff-view/bpmn-diff-view.ts
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/bpmn-io/services/diagram.xml.converter.ts
  src/modules/bpmn-xml-view/bpmn-xml-view.ts
  src/modules/diagram-detail/diagram-detail.ts
Labels: refactor

#910 ✨ Add the output of the order_script to the other scripts / Add more emojis
  dev_tooling/scripts/generate_changelog/README.md
  dev_tooling/scripts/generate_changelog/format_commit_messages.bash
  dev_tooling/scripts/generate_changelog/format_messages.bash
  dev_tooling/scripts/generate_changelog/get_fixed_issues.sh
  dev_tooling/scripts/generate_changelog/sort_and_format_merge_commits.sh
Labels: tooling

#917 💄 Fix wrong text overflow of the diff view summary
  src/modules/bpmn-diff-view/bpmn-diff-view.scss
Labels: UI, bugfix

#966 🐛 Enable tools from right toolbar on selection changed
  src/modules/diagram-tools-right/diagram-tools-right.ts
Labels: bugfix

#858 ✅ Compare View Tests and Karma removal
  aurelia_project/tasks/test.ts
  karma.conf.js
  package.json
  src/modules/bpmn-diff-view/bpmn-diff-view.html
  src/modules/status-bar/status-bar.html
  test/e2e/src/bpmnDiffView.spec.ts
  test/e2e/src/pages/bpmnDiffView.ts
  test/e2e/src/pages/solutionExplorer.ts
  test/e2e/src/pages/statusBar.ts
Labels: integration-test

#928 :construction_worker: Run End-To-End Tests Inside Docker On Jenkins
  Jenkinsfile
  package.json
  test/Dockerfile
  test/e2e/src/bpmnDiffView.spec.ts
  test/e2e/src/bpmnXmlView.spec.ts
  test/jenkins_e2e.sh
  test/protractor.conf.js
Labels: docker, integration-test

#982 🐛 Fix Label Creation When Adding Name Via Property Panel
  src/contracts/bpmnmodeler/IModeling.ts
  src/modules/property-panel/indextabs/general/sections/basics/basics.ts
Labels: bugfix

#980 🐛Update Think View; Show UserTasks of Correlation Instead of ProcessModel
  Jenkinsfile
  src/modules/process-list/process-list.html
  test/e2e/src/dashboard.spec.ts
  test/e2e/src/pages/processModel.ts
Labels: bugfix

#983 🐛 Fix Setting the Default Diff Mode
  src/modules/bpmn-diff-view/bpmn-diff-view.ts
Labels: bugfix

#987 🐛 Fix saving of invalid diagrams
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/diagram-detail/diagram-detail.ts
  src/modules/processdef-detail/processdef-detail.ts
Labels: bugfix
