Repository process-engine/bpmn-studio, pull requests merged in 2018-08, with the labels that each got.

#691 🔓Add dummy token fallback to authentication service
  package.json
  src/modules/authentication/authentication.service.ts
  src/modules/process-solution-panel/process-solution-panel.ts
Labels: enhancement

#701 Fix collapsing of the Solution Explorer
  package.json
  src/modules/process-solution-panel/process-solution-panel.ts
Labels: bugfix

#698 🐛Make BPMN-Studio start with the correct route
  src/main.ts
  src/modules/config-panel/config-panel.ts
  src/modules/management-api_client/index.ts
  src/modules/process-solution-panel/process-solution-panel.ts
  src/modules/status-bar/status-bar.ts
Labels: bugfix

#718 Add reset setup script
  dev_tooling/scripts/build_clean_setup.bash
  package.json
Labels: enhancement

#719 Fix undefined route params
  src/modules/dashboard/dashboard.ts
Labels: bug

#722 Show notification if identity server is offline
  src/modules/authentication/authentication.service.ts
Labels: enhancement

#726 Update skeleton-electron to 6.0.8
  package.json
Labels: bugfix

#713 Fix overlapping Modals
  src/modules/processdef-detail/processdef-detail.html
  src/modules/processdef-detail/processdef-detail.scss
  src/modules/processdef-detail/processdef-detail.ts
Labels: bugfix

#723 Show a modal when the user wants to deploy a diagram with unsaved changes
  src/modules/diagram-detail/diagram-detail.html
  src/modules/diagram-detail/diagram-detail.scss
  src/modules/diagram-detail/diagram-detail.ts
Labels: UX, enhancement

#735 Make the reset script usable with windows
  package.json
Labels: enhancement, tooling

#746 🐛🎨Fix Wrong Text Decoration at the Menu Bar
  src/modules/navbar/navbar.scss
Labels: bugfix

#782 Fix type annotation
  src/modules/form-widget/form-widget.ts
Labels: bug

#783 Add reinstall Script / Refactor reset script
  .gitignore
  dev_tooling/scripts/build_clean_setup.bash
  dev_tooling/scripts/reinstall_setup.bash
  dev_tooling/scripts/reset_setup.bash
  package.json
Labels: enhancement, tooling

#599 WIP :bug: Fix BPMN Validation
  src/modules/diagram-validation-service/DiagramValidationService.ts
Labels: bugfix

#785 🐛 Fix UserTask FormField type defaults to CustomType
  src/modules/property-panel/indextabs/forms/sections/basics/basics.ts
Labels: bugfix, discussion

#787 🐛Fix missing modal backdrop
  src/modules/processdef-detail/processdef-detail.html
  src/modules/processdef-detail/processdef-detail.ts
Labels: bugfix

#784 Add documentation for the scripts defined in the package.json
  README.md
Labels: documentation

#589 🐛Fix save dialog when leaving an unsaved diagram
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/diagram-detail/diagram-detail.ts
  src/modules/processdef-detail/processdef-detail.ts
Labels: bugfix

#800 ✨Preselect Diffmode
  src/modules/bpmn-diff-view/bpmn-diff-view.ts
  src/modules/status-bar/status-bar.ts
Labels: UX, enhancement, usability

#797 🐛Fix Empty ExtensionElements and Properties
  src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts
  src/modules/property-panel/indextabs/extensions/sections/process/process.ts
Labels: bugfix

#809 🔥♻️ Remove Paginator from the Process Definition list / tidy up Processsdef-List
  src/modules/processdef-list/processdef-list.html
  src/modules/processdef-list/processdef-list.scss
  src/modules/processdef-list/processdef-list.ts
Labels: code-quality, refactor

#807 🐛 Prevent the user from dragging around elements
  src/modules/navbar/navbar.scss
  src/modules/start-page/start-page.scss
Labels: UI, bugfix

#825 ♻️ Fix Download Menu On Windows
  electron_app/electron.js
Labels: windows

#814 ✅ Create integration test
  aurelia_project/tasks/e2e.ts
  package.json
  protractor.conf.js
  src/modules/navbar/navbar.html
  src/modules/process-solution-panel/process-solution-panel.html
  src/modules/processdef-list/processdef-list.html
  src/modules/status-bar/status-bar.html
  src/modules/user-login/user-login.html
  test/e2e/src/dashboard.spec.ts
  test/e2e/src/isLaunching.spec.ts
  test/e2e/src/navBar.spec.ts
  test/e2e/src/pages/dashboard.ts
  test/e2e/src/pages/general.ts
  test/e2e/src/pages/navBar.ts
  test/e2e/src/pages/processDefListPage.ts
  test/e2e/src/pages/processModel.ts
  test/e2e/src/pages/processdef-list-page.ts
  test/e2e/src/pages/settings.ts
  test/e2e/src/pages/solutionExplorer.ts
  test/e2e/src/pages/statusBar.ts
  test/e2e/src/processDefList.spec.ts
  test/e2e/src/solutionExplorer.spec.ts
  test/e2e/src/statusBar.spec.ts
  test/protractor.conf.js
Labels: integration-test

#812 🐛 Fix an error when trying to save a process that contains a UserTask with no FormFields
  src/contracts/bpmnmodeler/IElementRegistry.ts
  src/modules/processdef-detail/processdef-detail.ts
Labels: bugfix

#827 ♻️Rename Navbar Links
  src/modules/navbar/navbar.html
Labels: enhancement

#834 🐛Fix Updating Navbar When Changing Diagram
  src/modules/navbar/navbar.ts
  src/modules/process-solution-panel/process-solution-panel.ts
Labels: enhancement

#831 💄 Improve User Input Validation Names
  package.json
  src/contracts/user-input-validation/IUserInputValidationRule.ts
  src/contracts/user-input-validation/IUserInputValidationRuleset.ts
  src/contracts/user-input-validation/index.ts
  src/modules/process-solution-panel/process-solution-panel.ts
Labels: enhancement

#860 ✨Show Start and Deploy Button on Filesystem and ProcessEngine
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/modules/diagram-detail/diagram-detail.ts
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.ts
  src/modules/process-solution-panel/process-solution-panel.ts
  src/modules/processdef-detail/processdef-detail.ts
Labels: UI, enhancement

#859 ✅Align tests to renamed navbar links
  src/modules/navbar/navbar.html
  test/e2e/src/navBar.spec.ts
  test/e2e/src/pages/navBar.ts
Labels: enhancement, integration-test

#861 ✨Disable the color picker if the user does not select a diagram element.
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/diagram-tools-right/diagram-tools-right.html
  src/modules/diagram-tools-right/diagram-tools-right.scss
  src/modules/diagram-tools-right/diagram-tools-right.ts
Labels: UX, enhancement

#832 📝Add End-to-End Documentation
  .gitignore
  README.md
  dev_tooling/scripts/prepare_environment_for_integration_tests.sh
  integration-test.sh
Labels: documentation, integration-test

#850 📝 Add a note to install jq before running the get_fixed_issues script
  dev_tooling/scripts/generate_changelog/README.md
Labels: documentation

#851 ✅ Add dashboard tests
  package.json
  src/modules/dashboard/dashboard.html
  src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.html
  src/modules/process-list/process-list.html
  src/modules/task-list/task-list.html
  test/e2e/src/dashboard.spec.ts
  test/e2e/src/pages/dashboard.ts
  test/e2e/src/pages/processDefListPage.ts
  test/e2e/src/pages/processModel.ts
  test/e2e/src/pages/processdef-list-page.ts
  test/e2e/src/pages/solutionExplorer.ts
  test/e2e/src/processDefList.spec.ts
  test/e2e/src/solutionExplorer.spec.ts
  test/protractor.conf.js
Labels: integration-test

#902 🐛 Fix reinstall script
  dev_tooling/scripts/reinstall_setup.bash
  package.json
Labels: bugfix, tooling
