Repository process-engine/bpmn-studio, pull requests merged in 2018-11, with the labels that each got.

#1101 ✨ :sparkles: Add an Option to Create a Folder When Opening a Solution
  electron_app/electron.js
Labels: Enhancement

#1103 🐛:bug: Fix copy shortcut when using the xml view
  src/modules/bpmn-io/bpmn-io.ts
Labels: bugfix

#1096 🐛💄Fix wrong select design
  src/modules/property-panel/indextabs/forms/sections/basics/basics.html
  src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.html
  src/modules/property-panel/indextabs/general/sections/error-event/error-event.html
  src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.html
  src/modules/property-panel/indextabs/general/sections/message-event/message-event.html
  src/modules/property-panel/indextabs/general/sections/message-task/message-task.html
  src/modules/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.html
  src/modules/property-panel/indextabs/general/sections/service-task/service-task.html
  src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.html
  src/modules/property-panel/indextabs/general/sections/timer-event/timer-event.html
  src/modules/property-panel/styles/sections.scss
Labels: bugfix

#1077 ✨Remove empty extension properties after creating
  package.json
  src/modules/property-panel/indextabs/extensions/sections/basics/basics.html
  src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts
  src/modules/property-panel/indextabs/extensions/sections/process/process.html
  src/modules/property-panel/indextabs/extensions/sections/process/process.ts
Labels: Enhancement

#1097 🐛 :bug: fix non updating token viewer
  package.json
  src/modules/inspect-correlation/components/token-viewer/token-viewer.html
  src/modules/inspect-correlation/components/token-viewer/token-viewer.ts
Labels: bugfix

#1116 ✨Add new gitmoji emojis to release format script
  dev_tooling/scripts/generate_changelog/format_messages.bash
Labels: Tooling

#1153 🐛Fix PropertyPanel after collapse a pool
  src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts
  src/modules/design/property-panel/indextabs/general/sections/pool/pool.ts
Labels: bugfix

#1154 🐛Prevent saving a diagram with multiple participants
  src/modules/design/bpmn-io/bpmn-io.ts
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/design/processdef-detail/processdef-detail.ts
Labels: bugfix

#1157 🐛Fix UserTask FormField IDs are not Unique Bug
  src/contracts/bpmnmodeler/IDescriptor.ts
  src/contracts/bpmnmodeler/IInternalEvent.ts
  src/contracts/bpmnmodeler/bpmnElements/IPropertiesElement.ts
  src/contracts/bpmnmodeler/index.ts
  src/modules/design/bpmn-io/bpmn-io.ts
Labels: bugfix
