Repository process-engine/bpmn-studio, pull requests merged in 2018-07, with the labels that each got.

#508 Check if the diagram is valid before saving
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/processdef-detail/processdef-detail.html
  src/modules/processdef-detail/processdef-detail.ts
Labels: enhancement

#513 Improve the resolution when printing or exporting a diagram as an image
  src/modules/processdef-detail/processdef-detail.ts
Labels: enhancement

#556 🐛Fix Saving Bug on Error-Event
  src/modules/property-panel/indextabs/extensions/sections/process/process.ts
  src/modules/property-panel/indextabs/general/sections/error-event/error-event.ts
  src/modules/property-panel/indextabs/general/sections/escalation-event/escalation-event.ts
  src/modules/property-panel/indextabs/general/sections/message-event/message-event.ts
  src/modules/property-panel/indextabs/general/sections/signal-event/signal-event.ts
Labels: bug

#554 🐛Fix unable to create property on usertask bug
  src/contracts/bpmnmodeler/IModeling.ts
  src/contracts/bpmnmodeler/IShape.ts
  src/contracts/bpmnmodeler/bpmnElements/IPropertiesElement.ts
  src/contracts/bpmnmodeler/bpmnElements/IPropertyElement.ts
  src/contracts/bpmnmodeler/bpmnElements/index.ts
  src/contracts/propertypanel/ISection.ts
  src/modules/processengine/processengine.service.ts
  src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts
  src/modules/property-panel/indextabs/extensions/sections/process/process.ts
  src/modules/task-list/task-list.ts
Labels: bug

#582 🐛 :bug: Check For XML File Signature Before Opening Diagrams
  src/contracts/diagram-validation-service/IDiagramValidationRule.ts
  src/contracts/diagram-validation-service/IDiagramValidationRuleSet.ts
  src/contracts/diagram-validation-service/IDiagramValidationRules.ts
  src/contracts/diagram-validation-service/IDiagramValidationService.ts
  src/contracts/diagram-validation-service/IDiagramValidator.ts
  src/contracts/diagram-validation-service/index.ts
  src/contracts/index.ts
  src/main.ts
  src/modules/diagram-validation-service/DiagramValidationService.ts
  src/modules/diagram-validation-service/DiagramValidator.ts
  src/modules/diagram-validation-service/index.ts
  src/modules/process-solution-panel/process-solution-panel.html
  src/modules/process-solution-panel/process-solution-panel.ts
Labels: bug

#594 🐛 :bug: Fix Multiple Imports Not Working
  src/modules/processdef-list/processdef-list.ts
Labels: firefox-only

#588 🐛 Fix Diff And Xml View (Firefox)
  src/modules/bpmn-io/bpmn-io.ts
  src/modules/property-panel/property-panel.ts
Labels: bug, firefox-only

#587 login using identity server (electron)
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  bin/bpmn-studio.js
  config/development/iam/iam_service.json
  config/development/process_engine/flow_node_instance_repository.json
  config/development/process_engine/process_model_repository.json
  electron_app/electron.js
  index.html
  package.json
  src/app.ts
  src/environment.ts
  src/modules/authentication/new_authentication.service.ts
  src/modules/authentication/open-id/open-id-signin-response.ts
  src/modules/authentication/open-id/open-id-url-utility.ts
Labels: enhancement

#632 Refactor navigation
  package.json
  src/app.ts
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.scss
  src/modules/navbar/navbar.ts
  src/modules/process-list/process-list.html
  src/modules/process-solution-panel/process-solution-panel.html
  src/modules/process-solution-panel/process-solution-panel.ts
  src/modules/processdef-detail/processdef-detail.ts
  src/modules/processdef-list/processdef-list.ts
  src/modules/property-panel/indextabs/general/sections/call-activity/call-activity.ts
  src/modules/status-bar/status-bar.ts
  src/modules/task-dynamic-ui/task-dynamic-ui.ts
  src/modules/task-list/task-list.html
  src/modules/waiting-room/waiting-room.ts
Labels: enhancement

#662 Cleanup leftovers from the `AuthenticationService` duplicates.
  src/app.ts
  src/contracts/authentication/IAuthenticationService.ts
  src/modules/authentication/authentication.service.ts
  src/modules/authentication/index.ts
  src/modules/config-panel/config-panel.ts
  src/modules/dashboard/dashboard.ts
  src/modules/diagram-detail/diagram-detail.ts
  src/modules/process-list/process-list.ts
  src/modules/process-solution-panel/process-solution-panel.ts
  src/modules/processdef-detail/processdef-detail.ts
  src/modules/processdef-list/processdef-list.ts
  src/modules/task-list/task-list.ts
  src/modules/user-login/user-login.ts
Labels: enhancement

#669 Fix userData folder path in dev environment
  .gitignore
  config/development/application/application_service.json
  config/development/caching/cache_repository.json
  config/development/data_sources/localstorage.json
  config/development/datastore/router.json
  config/development/datastore/service.json
  config/development/default_data/datastore.json
  config/development/feature/feature_service.json
  config/development/http/http_extension.json
  config/development/iam/auth_service.json
  config/development/iam/claim_service/claims/default_namespace/default_permissions.json
  config/development/iam/claim_service/claims/default_namespace/entity_types/user.json
  config/development/iam/iam_service.json
  config/development/iam/identity_service.json
  config/development/iam/jwt_token_adapter.json
  config/development/iam/router.json
  config/development/iam/token_service.json
  config/development/messagebus/faye.json
  config/development/messagebus/router.json
  config/development/process_engine/process_engine_service.json
  config/development/process_engine/router.json
  config/development/process_engine/timer_repository.json
  config/development/routing/routing_service.json
  config/development/security/asymmetric_encryption_service.json
  config/development/security/hash_service.json
  config/development/security/pki_service.json
  config/development/security/security_service.json
  config/development/security/symmetric_encryption_service.json
  config/development/services/mail.json
  config/development/timing/timing_service.json
  electron_app/electron.js
Labels: bug, enhancement
