Repository process-engine/bpmn-studio, pull requests merged in 2018-12, with the labels that each got.

#1162 ♻️ 🐛 Refactor and Bugfixes
  src/contracts/solution-explorer/ISolutionService.ts
  src/modules/config-panel/config-panel.ts
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/inspect/heatmap/heatmap.html
  src/modules/inspect/heatmap/heatmap.scss
  src/modules/inspect/heatmap/heatmap.ts
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.ts
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
  src/services/SolutionService.ts
Labels: Refactor, bugfix

#1188 🐛Fix Setting Correct Solution and Diagram on Live Execution Tracker
  src/modules/live-execution-tracker/live-execution-tracker.ts
Labels: bugfix

#1186 🐛Fix Settings Update Navigate
  src/modules/config-panel/config-panel.ts
  src/modules/design/diagram-detail/diagram-detail.ts
Labels: bugfix

#1204 ✨Start Process With Custom CorrelationId and Payload
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/app.scss
  src/modules/design/bpmn-io/bpmn-io.ts
  src/modules/design/diagram-detail/diagram-detail.html
  src/modules/design/diagram-detail/diagram-detail.scss
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.scss
  src/modules/navbar/navbar.ts
Labels: Feature

#1209 🐛 Fix Displaying Dynamic UI Modal
  src/modules/live-execution-tracker/live-execution-tracker.html
Labels: bugfix

#1218 🐛 Fix duplicate highlight when two diagrams in two different solution had the same name
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
Labels: bugfix

#1217 🏗:building_construction: Refactor Architecture Of Design
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/app.ts
  src/modules/design/bpmn-io/bpmn-io.html
  src/modules/design/bpmn-io/bpmn-io.ts
  src/modules/design/bpmn-xml-view/bpmn-xml-view.html
  src/modules/design/bpmn-xml-view/bpmn-xml-view.ts
  src/modules/design/design.html
  src/modules/design/design.scss
  src/modules/design/design.ts
  src/modules/design/diagram-detail/diagram-detail.html
  src/modules/design/diagram-detail/diagram-detail.scss
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/design/property-panel/indextabs/general/sections/call-activity/call-activity.ts
  src/modules/design/property-panel/property-panel.ts
  src/modules/inspect/heatmap/heatmap.ts
  src/modules/inspect/heatmap/services/heatmap.service.ts
  src/modules/inspect/inspect.html
  src/modules/inspect/inspect.ts
  src/modules/inspect/process-list/process-list.html
  src/modules/inspect/task-list/task-list.html
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.ts
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
  src/modules/status-bar/status-bar.ts
  src/modules/think/processdef-list/processdef-list.ts
  test/e2e/src/bpmnDiffView.spec.ts
  test/e2e/src/pages/design.ts
  test/e2e/src/pages/processModel.ts
Labels: Refactor
