Repository process-engine/bpmn-studio, pull requests merged in 2019-03, with the labels that each got.

#1389 ✨Add PE Version to Solution's Title
  src/contracts/solution-explorer/ISolutionEntry.ts
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
Labels: Feature

#1331 ✨Diff Against Other Diagrams
  src/contracts/solution-explorer/ISolutionService.ts
  src/modules/design/bpmn-diff-view/bpmn-diff-view.html
  src/modules/design/bpmn-diff-view/bpmn-diff-view.scss
  src/modules/design/bpmn-diff-view/bpmn-diff-view.ts
  src/modules/design/design.html
  src/modules/design/design.scss
  src/modules/design/design.ts
  src/modules/status-bar/status-bar.html
  src/modules/status-bar/status-bar.scss
  src/services/solution-service/SolutionService.ts
  test/e2e/src/diffView.spec.ts
  test/e2e/src/pages/diffView.ts
Labels: Feature

#1423 ✨Show Version and Release Notes in Auto Updater
  electron_app/electron.js
  src/main.ts
Labels: Feature

#1428 🔥 Remove unused settings from old PE implementation
  src/main.ts
Labels: Code Quality, Refactor

#1425 ✏️ Fix Typos in Issue Template
  .github/ISSUE_TEMPLATE.md
Labels: Tooling

#1434 ♻️ Refactor the Dashboards ProcessList and TaskList
  src/modules/inspect/process-list/process-list.html
  src/modules/inspect/process-list/process-list.ts
  src/modules/inspect/task-list/task-list.html
  src/modules/inspect/task-list/task-list.ts
  src/modules/navbar/navbar.ts
Labels: Code Quality, Refactor

#1430 ✨Sort the Diagrams in all Opened Solutions
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
Labels: Enhancement, Feature

#1438 ♻️ Make linter errors more prominent
  package-lock.json
  package.json
  src/app.scss
  src/modules/design/bpmn-io/bpmn-io.html
  src/modules/design/bpmn-io/bpmn-io.scss
Labels: Bad User Experience, Code Quality

#1442 🐛 Fix Bug Where Linter Summary is Not Updated Automatically
  src/modules/design/bpmn-io/bpmn-io.ts
Labels: bugfix

#1437 🔧 Improve e2e Test Log
  Jenkinsfile
  package-lock.json
  package.json
  test/protractor.conf.js
Labels: Tooling
