Repository process-engine/bpmn-studio, pull requests merged in 2019-07, with the labels that each got.

#1531 🐛Fix web version
  package-lock.json
  src/main.ts
  src/modules/design/bpmn-io/repositories/DiagramExportRepository.ts
  src/modules/inspect/process-list/process-list.ts
  src/services/notification-service/notification.service.ts
  tsconfig.json
Labels: bugfix

#1529 ✨Make Solutions Collapsible
  src/contracts/solution-explorer/ISolutionEntry.ts
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.scss
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
Labels: Feature

#1534 ♻️🐛 Do not Generate a New Camunda Property Objects
  src/modules/design/property-panel/indextabs/extensions/sections/basics/basics.ts
  src/modules/design/property-panel/indextabs/general/sections/service-task/components/external-task/external-task.ts
  src/modules/design/property-panel/indextabs/general/sections/service-task/components/http-service-task/http-service-task.ts
  src/modules/design/property-panel/indextabs/general/sections/service-task/components/service-task-service/service-task-service.ts
  src/modules/design/property-panel/indextabs/general/sections/service-task/service-task.ts
Labels: bugfix

#1580 🐛 Fix bug where the delete diagram modal is still open after deletion
  src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts
Labels: bugfix

#1581 ✨Add empty activities to task list
  src/modules/inspect/task-list/task-list.html
  src/modules/inspect/task-list/task-list.ts
  src/modules/live-execution-tracker/live-execution-tracker.ts
Labels: Enhancement

#1582 💄Unify font size
  src/modules/design/bpmn-io/bpmn-io.scss
  src/modules/design/bpmn-xml-view/bpmn-xml-view.scss
  src/modules/design/property-panel/indextabs/general/sections/basics/basics.scss
  src/modules/design/property-panel/property-panel.scss
  src/modules/inspect/heatmap/heatmap.html
  src/modules/inspect/heatmap/heatmap.scss
  src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.html
  src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.scss
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.html
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.html
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.scss
  src/modules/inspect/inspect-correlation/components/inspect-panel/inspect-panel.scss
  src/modules/inspect/token-viewer/token-viewer.scss
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss
  src/modules/start-page/start-page.html
  src/modules/start-page/start-page.scss
  src/modules/status-bar/status-bar.scss
Labels: UI

#1602 ✨Add total count to dashboard
  src/modules/inspect/cronjob-list/cronjob-list.html
  src/modules/inspect/cronjob-list/cronjob-list.scss
  src/modules/inspect/process-list/process-list.html
  src/modules/inspect/process-list/process-list.scss
  src/modules/inspect/task-list/task-list.html
  src/modules/inspect/task-list/task-list.scss
Labels: Bad User Experience

#1610 💄Reworking unify font size
  src/modules/inspect/cronjob-list/cronjob-list.html
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.scss
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.scss
  src/modules/inspect/process-list/process-list.html
  src/modules/inspect/task-list/task-list.html
Labels: UI

#1604 ✨Loading spinner Inspect-Correlation
  aurelia_project/environments/dev.ts
  src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.html
  src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.scss
  src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts
  src/modules/inspect/inspect-correlation/inspect-correlation.ts
Labels: Bad User Experience
