Repository process-engine/bpmn-studio, pull requests merged in 2019-01, with the labels that each got.

#1233 🐛 Fix Unsaved Change Modal When Switching to the Diff- or XML View
  aurelia_project/environments/dev.ts
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/status-bar/status-bar.ts
Labels: bugfix

#1235 🐛 Fix Status Bar Buttons When Navigating Back from the Diff View Using the Back Button
  src/modules/status-bar/status-bar.ts
Labels: bugfix

#1238 🐛 Fix Wrong Status Bar Buttons When Using the Back Button
  src/modules/status-bar/status-bar.ts
Labels: bugfix

#1223 🔥:fire: Remove Unnecessary Environment Files
  aurelia_project/environments/prod.ts
  aurelia_project/environments/stage.ts
  aurelia_project/tasks/build.ts
  aurelia_project/tasks/copy-files.ts
  aurelia_project/tasks/e2e.ts
  aurelia_project/tasks/e2eCrossbrowser.ts
  aurelia_project/tasks/e2eDocker.ts
  aurelia_project/tasks/process-css.ts
  aurelia_project/tasks/process-markup.ts
  aurelia_project/tasks/run.ts
  aurelia_project/tasks/transpile.ts
  aurelia_project/tasks/watch.ts
  package.json
Labels: Refactor

#1240 🐛:bug: Fix e2e Tests for XML View
  test/e2e/src/bpmnXmlView.spec.ts
Labels: bugfix

#1221 ✨Allow Multiple Remote Solutions
  src/contracts/index.ts
  src/contracts/navigation/AureliaNavigationResult.ts
  src/contracts/navigation/index.ts
  src/contracts/solution-explorer/ISolutionService.ts
  src/main.ts
  src/modules/config-panel/config-panel.html
  src/modules/config-panel/config-panel.ts
  src/modules/design/design.ts
  src/modules/design/diagram-detail/diagram-detail.html
  src/modules/design/diagram-detail/diagram-detail.scss
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/design/property-panel/indextabs/general/repository/general.repository.ts
  src/modules/inspect/inspect.ts
  src/modules/inspect/process-list/process-list.html
  src/modules/inspect/process-list/process-list.ts
  src/modules/inspect/task-list/task-list.html
  src/modules/inspect/task-list/task-list.ts
  src/modules/live-execution-tracker/live-execution-tracker.ts
  src/modules/management-api_client/index.ts
  src/modules/navbar/navbar.ts
  src/modules/solution-explorer-services/RefreshingSolutionExplorerService.ts
  src/modules/solution-explorer-services/index.ts
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.html
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
  src/modules/status-bar/status-bar.html
  src/modules/status-bar/status-bar.ts
  src/modules/think/processdef-list/processdef-list.html
  src/modules/think/processdef-list/processdef-list.ts
  src/services/SolutionService.ts
  test/e2e/src/dashboard.spec.ts
  test/e2e/src/processDefList.spec.ts
Labels: Feature

#1244 🐛 Fix uncaught exception when initially loading solutions
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
Labels: bugfix

#1222 ✨Add Export Functionality On Inspect-Cor…
  aurelia_project/environments/dev.ts
  src/modules/design/bpmn-io/bpmn-io.ts
  src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts
  src/modules/inspect/inspect.ts
  src/modules/navbar/navbar.html
  src/modules/navbar/navbar.scss
  src/modules/navbar/navbar.ts
Labels: Feature

#1255 🐛 Don't Open Single Diagrams Several Times
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
Labels: bugfix

#1253 ✨InitialToken From StartEvent Annotation
  src/contracts/bpmnmodeler/IShape.ts
  src/modules/design/diagram-detail/diagram-detail.html
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/inspect/process-list/process-list.html
Labels: Feature

#1257 ✨ Navigate away, if the user closes the Solution, on whose detail view he is currently on
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
Labels: bugfix

#1283 🐛Fix Copy on Xml
  aurelia_project/environments/dev.ts
  src/modules/design/bpmn-io/bpmn-io.ts
  src/modules/design/design.ts
Labels: bugfix

#1261 🚸 Improve error message when trying to open an already opened remote Solution
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
Labels: UX

#1284 🐛Fix Participant ID Bug
  src/contracts/bpmnmodeler/IInternalEvent.ts
  src/modules/design/bpmn-io/bpmn-io.ts
Labels: bugfix

#1278 🔥♻️Remove getIdentity Method
  src/modules/dynamic-ui-wrapper/dynamic-ui-wrapper.ts
  src/modules/inspect/dashboard/dashboard.ts
  src/modules/inspect/heatmap/contracts/IHeatmap.Repository.ts
  src/modules/inspect/heatmap/contracts/IHeatmap.Service.ts
  src/modules/inspect/heatmap/heatmap.ts
  src/modules/inspect/heatmap/repositories/heatmap.mock.repository.ts
  src/modules/inspect/heatmap/repositories/heatmap.repository.ts
  src/modules/inspect/heatmap/services/heatmap.service.ts
  src/modules/inspect/inspect.html
  src/modules/inspect/inspect.ts
  src/modules/live-execution-tracker/live-execution-tracker.html
  src/modules/live-execution-tracker/live-execution-tracker.ts
  src/modules/task-dynamic-ui/task-dynamic-ui.ts
  src/modules/task-list-container/task-list-container.ts
  test/e2e/src/dashboard.spec.ts
  test/e2e/src/pages/dashboard.ts
Labels: Refactor
