Repository process-engine/bpmn-studio, pull requests merged in 2019-02, with the labels that each got.

#1327 🐛Fix RegEx for URLs
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
Labels: bugfix

#1316 🔧 Do not rebuild sqlite3 Dependency on Every Dev. Start
  README.md
  package.json
Labels: Tooling

#1340 🔥Remove Choose-Dialog
  src/contracts/choose-dialog/IChooseDialogOption.ts
  src/contracts/choose-dialog/index.ts
  src/contracts/index.ts
  src/modules/choose-dialog/choose-dialog.html
  src/modules/choose-dialog/choose-dialog.scss
  src/modules/choose-dialog/choose-dialog.ts
Labels: Refactor

#1336 ♻️Refactor Usage of Modals
  src/app.scss
  src/main.ts
  src/modules/custom_elements/modal/modal.html
  src/modules/custom_elements/modal/modal.scss
  src/modules/design/design.html
  src/modules/design/diagram-detail/diagram-detail.scss
  src/modules/live-execution-tracker/live-execution-tracker.html
  src/modules/live-execution-tracker/live-execution-tracker.scss
  src/modules/live-execution-tracker/live-execution-tracker.ts
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.scss
  src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.html
  src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.scss
  src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
Labels: Refactor

#1344 🐛 Fix Binding on Remote Solution Uri
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.html
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
Labels: bugfix

#1342 ♻️Move Services to Services Folder
  src/app.ts
  src/main.ts
  src/modules/config-panel/config-panel.ts
  src/modules/confirm-widget/confirm-widget.ts
  src/modules/design/bpmn-diff-view/bpmn-diff-view.ts
  src/modules/design/bpmn-io/bpmn-io.ts
  src/modules/design/design.ts
  src/modules/design/diagram-detail/diagram-detail.ts
  src/modules/design/diagram-tools-right/diagram-tools-right.ts
  src/modules/form-widget/form-widget.ts
  src/modules/inspect/dashboard/dashboard.ts
  src/modules/inspect/inspect-correlation/components/diagram-viewer/diagram-viewer.ts
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/correlation-list/correlation-list.ts
  src/modules/inspect/inspect-correlation/components/inspect-panel/components/log-viewer/log-viewer.ts
  src/modules/inspect/inspect.ts
  src/modules/inspect/process-list/process-list.ts
  src/modules/inspect/task-list/task-list.ts
  src/modules/live-execution-tracker/live-execution-tracker.ts
  src/modules/navbar/navbar.ts
  src/modules/solution-explorer/solution-explorer-list/solution-explorer-list.ts
  src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts
  src/modules/solution-explorer/solution-explorer-solution/delete-diagram-modal/delete-diagram-modal.ts
  src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts
  src/modules/task-dynamic-ui/task-dynamic-ui.ts
  src/modules/task-list-container/task-list-container.ts
  src/modules/think/think.ts
  src/services/authentication-service/electron.oidc.authentication.service.ts
  src/services/authentication-service/index.ts
  src/services/authentication-service/open-id/open-id-signin-response.ts
  src/services/authentication-service/open-id/open-id-url-utility.ts
  src/services/authentication-service/web.oidc.authentication.service.ts
  src/services/date-service/date.service.ts
  src/services/diagram-creation-service/DiagramCreationService.ts
  src/services/diagram-creation-service/index.ts
  src/services/diagram-validation-service/DiagramValidationService.ts
  src/services/diagram-validation-service/DiagramValidator.ts
  src/services/diagram-validation-service/index.ts
  src/services/dynamic-ui-service/dynamic-ui.service.ts
  src/services/dynamic-ui-service/index.ts
  src/services/elementname-service/elementname.service.ts
  src/services/notification-service/index.ts
  src/services/notification-service/notification.service.ts
  src/services/solution-explorer-services/DiagramTrashFolderService.ts
  src/services/solution-explorer-services/SingleDiagramsSolutionExplorerService.ts
  src/services/solution-explorer-services/SolutionExplorerServiceFactory.ts
  src/services/solution-explorer-services/index.ts
  src/services/solution-service/SolutionService.ts
  src/services/solution-service/index.ts
Labels: Refactor
